"""Add CustomerPersonaQuestionnaire table

Revision ID: 0827003e54dc
Revises: 370d45dd2b2a
Create Date: 2025-05-25 16:52:37.472546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0827003e54dc'
down_revision: Union[str, None] = '370d45dd2b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_persona_questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q_uuid', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('input_type', sa.String(length=100), nullable=True),
    sa.Column('range', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_persona_questionnaire_id'), 'customer_persona_questionnaire', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_persona_questionnaire_id'), table_name='customer_persona_questionnaire')
    op.drop_table('customer_persona_questionnaire')
    # ### end Alembic commands ###
