"""Add CustomerPersonaQuestionnaire table for customerboard questions

Revision ID: 370d45dd2b2a
Revises: fe032e194ae3
Create Date: 2025-05-25 15:17:39.740372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370d45dd2b2a'
down_revision: Union[str, None] = 'fe032e194ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
