"""Add IdeaPersonaLink table for linking personas to ideas

Revision ID: 52976eaf8e81
Revises: 6806c503eb2d
Create Date: 2025-06-14 13:04:09.285031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52976eaf8e81'
down_revision: Union[str, None] = '6806c503eb2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_persona_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideaboard.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['customer_personas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idea_persona_links_id'), 'idea_persona_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idea_persona_links_id'), table_name='idea_persona_links')
    op.drop_table('idea_persona_links')
    # ### end Alembic commands ###
