"""Sync models with database

Revision ID: 5c580fee5e8a
Revises: dfb7f3127fcb
Create Date: 2025-01-28 10:49:54.941511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c580fee5e8a'
down_revision: Union[str, None] = 'dfb7f3127fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
