"""add_stripe_fields_to_user

Revision ID: 8d7c130e0e77
Revises: dca1690aa07f
Create Date: 2025-05-18 15:32:23.310235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7c130e0e77'
down_revision: Union[str, None] = 'dca1690aa07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_plan', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('current_period_end', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('trial_end', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['stripe_customer_id'])
    op.create_unique_constraint(None, 'users', ['stripe_subscription_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'trial_end')
    op.drop_column('users', 'current_period_end')
    op.drop_column('users', 'stripe_subscription_id')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'subscription_plan')
    # ### end Alembic commands ###
