"""Add category column to CustomerPersonaQuestionnaire

Revision ID: cc260d87fe69
Revises: 0827003e54dc
Create Date: 2025-05-25 20:30:06.873507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc260d87fe69'
down_revision: Union[str, None] = '0827003e54dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_persona_questionnaire', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_persona_questionnaire', 'category')
    # ### end Alembic commands ###
