"""Update CustomerPersona fields to match schema

Revision ID: dbd17723a379
Revises: cc260d87fe69
Create Date: 2025-05-25 21:59:04.491502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd17723a379'
down_revision: Union[str, None] = 'cc260d87fe69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
