"""initial_schema_after_pycache_clean

Revision ID: e2e57bd0aefb
Revises: 
Create Date: 2025-05-10 01:54:42.845266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.exc import ProgrammingError


# revision identifiers, used by Alembic.
revision: str = 'e2e57bd0aefb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if users table exists
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    
    if 'users' not in tables:
        # Table doesn't exist - this migration should be skipped for fresh databases
        # Tables should be created via create_tables.py first, then stamp with: alembic stamp head
        print("⚠️  Note: 'users' table does not exist. Skipping migration.")
        print("   For fresh databases, create tables first with: python create_tables.py")
        print("   Then stamp the database with: alembic stamp head")
        return
    
    # Check if username column already exists
    columns = [col['name'] for col in inspector.get_columns('users')]
    if 'username' not in columns:
        op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
        op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    else:
        print("⚠️  Note: 'username' column already exists. Skipping.")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    
    if 'users' not in tables:
        return
    
    columns = [col['name'] for col in inspector.get_columns('users')]
    if 'username' in columns:
        op.drop_index(op.f('ix_users_username'), table_name='users')
        op.drop_column('users', 'username')
    # ### end Alembic commands ###
