"""Expand CustomerPersona fields for Figma 8-section persona

Revision ID: fe032e194ae3
Revises: 8d7c130e0e77
Create Date: 2025-05-25 03:30:32.997483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe032e194ae3'
down_revision: Union[str, None] = '8d7c130e0e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
